### ISSUE TITLE
Seafile

### ISSUE THREAD

**Issue by raduab** [cznweb/genesis#294]
Please add seafile private cloud as a plugin. It's faster than owncloud. see it at www.seafile.com

**Comment by peakwinter** [comment]
Due to its complex backend and extensive difficulty in successful maintenance, I will not be able to support an official Seafile plugin at this time. I am however putting a good effort into several alternatives including Syncthing. If someone is interested in helping develop a Seafile app for arkOS feel free to contact me and I'll help as much as possible.

(see [this](https://bbs.arkos.io/t/installation-problem-with-seafile-version-4-0-6-1-was-3-0-2-3/1617))
